#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri May 26 13:30:10 2017
Base class for Curriculum Learning approaches. A Curriculum composed of only the target task is built.
@author: Felipe Leno
"""
import abc

class Curriculum(object):
    """ This is the base class for all Curriculum Learning implementations.

    """
    __metaclass__ = abc.ABCMeta
    
   
    def __init__(self, seed=12345):
        pass
        

    
    def set_agent(self,agent):
        """This method can be used to get a reference to the learning agent"""
        pass      
        

    @abc.abstractmethod
    def generate_curriculum(target_task, workFolder):
        """ The Curriculum is generated by this function (stored internally) """
        pass
     
        
    @abc.abstractmethod
    def empty_curriculum(self):
        """ Returns if the curriculum still has an untrained task """
        pass
    
    @abc.abstractmethod    
    def draw_task(self):
        """ Get the next task in the curriculum """
        pass
    
 

